services:
  - type: web
    name: phishing-api-detection
    env: python
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14

    buildCommand: |
      pip install -r requirements.txt
      python download_model.py

    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
